USE [master]
GO

/****** Object:  Database [FoodServe]    Script Date: 21/02/2024 11:20:43 ******/
CREATE DATABASE [FoodServe] ON  PRIMARY 
( NAME = N'FoodServe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\FoodServe.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FoodServe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\FoodServe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FoodServe] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodServe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FoodServe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FoodServe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FoodServe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FoodServe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FoodServe] SET ARITHABORT OFF 
GO

ALTER DATABASE [FoodServe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FoodServe] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FoodServe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FoodServe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FoodServe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FoodServe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FoodServe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FoodServe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FoodServe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FoodServe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FoodServe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FoodServe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FoodServe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FoodServe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FoodServe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FoodServe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FoodServe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FoodServe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FoodServe] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FoodServe] SET  MULTI_USER 
GO

ALTER DATABASE [FoodServe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FoodServe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FoodServe] SET  READ_WRITE 
GO


